### ISSUE TITLE
소멸자

### ISSUE THREAD

**Issue by imeubug** [devouring-algorithm-ds/algorithm-study-s1#6]
https://github.com/devouring-algorithm-ds/algorithm-study-s1/blob/b920e8ab315dc40ae9cd9d1e2dca95e376ccaa3d/devMS/week1/implementation/singly-linked-list/linkedlist.h#L31-L34

@minsunny5 

Head (1) -> 2 -> 3
이렇게 리스트가 있는 상태에서 프로그램이 종료되어 소멸자를 호출할 경우 head가 지워지게 되죠?
하지만 2 -> 3은 메모리 상태에 그대로 남게되어 memory leak(메모리 누수)가 발생합니다. 
노드 하나하나 제거해주어야 합니다.

**Comment by minsunny5** [comment]
음..그럼 아예 노드를 전부 없애는 함수를 하나 만드는게 좋겠네요. 감사합니다~
