### ISSUE TITLE
removeFront() and removeLast() 

### ISSUE THREAD

**Issue by imeubug** [devouring-algorithm-ds/algorithm-study-s1#7]
https://github.com/devouring-algorithm-ds/algorithm-study-s1/blob/b920e8ab315dc40ae9cd9d1e2dca95e376ccaa3d/devMS/week1/implementation/singly-linked-list/linkedlist.h#L69-L95

@minsunny5 

리스트가 비어있는 경우 `head`는 이미 비어있는데 `head->next`를 참조하므로 segmentation fault가 발생합니다.
리스트가 비어있는 상태에서 `removeFront()` 또는 `removeLast()`를 실행해보세요.

`head->next`가 아닌 `head`가 nullptr인지 확인하는 작업이 필요해요.

**Comment by minsunny5** [comment]
맞네요. 비어있는 상태에서 체크를 안해봤네요. 체크해서 푸시하겠습니다~~
