### ISSUE TITLE
C++에서의 NULL 

### ISSUE THREAD

**Issue by imeubug** [devouring-algorithm-ds/algorithm-study-s1#8]
https://github.com/devouring-algorithm-ds/algorithm-study-s1/blob/b920e8ab315dc40ae9cd9d1e2dca95e376ccaa3d/devMS/week1/implementation/singly-linked-list/linkedlist.h#L27-L30

@minsunny5 

C의 경우`NULL`은 `(void*)0`으로 연산되지만 C++에서는 그냥 숫자 `0`입니다.  C++에서 포인터를 다룰때는 `NULL`보다는 `nullptr`를 사용하는 것이 좋아요.
```cpp
next = nullptr;
```

**Comment by minsunny5** [comment]
nullptr이 c++11에 있는 키워드라고 하더라구요. 제가 학교서버에서 코딩을 하고 있는데 좀 예전버전이라 그런지 nullptr이 키워드로 인식이 안돼서 어쩔 수 없이 NULL을 썼습니다. 물론 nullptr이 더 좋을거같아요..!

**Comment by imeubug** [comment]
아하 학교서버 환경이군요. 되게 오래되었나 보네요. 알고 사용하는 것과 모르는 것은 별개이니, 알고 계시다면 괜찮습니다!

**Comment by minsunny5** [comment]
c++11이 기본으로 설정이 안되니까 g++ -std=c++11 main.cpp 이 커맨드로 컴파일 하니까 되네요. 수정하도록 할게요!

**Comment by imeubug** [comment]
매번 타이핑하는것이 귀찮으시다면 .bashrc 혹은 .zshrc 파일이 루트폴더에 있을텐데요. 거기에 
```bash
alias g++="g++ -std=c++11"
```
저장하고 터미널 재시작 해주세요. 그럼 이제부터는 g++만 사용해도 저절로 `g++ -std=c++11`가 적용이 됩니다.
