### ISSUE TITLE
스타일 관련??

### ISSUE THREAD

**Issue by imeubug** [devouring-algorithm-ds/algorithm-study-s1#9]
https://github.com/devouring-algorithm-ds/algorithm-study-s1/blob/e4034efa7a77cd59f5f03a4eb67215abdea8024d/Coalery/week1/implementation/SinglyLinkedList/SinglyLinkedList.java#L115-L116

@Coalery 

자바는 잘 모르지만 😅 잘 구현하신 것 같아요.

위 참고한 코드부분에서 아래처럼 해도 되지 않았을까? 하고 의견을 던져봅니다.
```java
temp.next = targetNode.next;
// 또는 
temp.next = temp.next.next;
```

**Comment by Coalery** [comment]
next 두번 쓰니 제가 못알아봐서 그렇습니다.. ㅠㅠㅜ
